@startuml

class MainActivity {
    public static String APP_NAME = "TFM_PoseTest";
    public static String ZIP_NAME = "TFM_PoseTest.zip";
    public static File outputFolderFile;
    private Button executeButton;
    private Button shareButton;
    private Button exitButton;

    protected void onCreate(Bundle)
    private void executeModels()
    private void generateOutputZipFile()

}

abstract class TensorFlowLiteModel {
    protected static int NUM_KEYPOINTS_PREDICTION = 17;
    protected MainActivity mainActivity;
    protected TextView component;
    protected String modelName;
    protected String fileModelName;
    protected String outputPredictionsFileName;
    protected String outputPerformanceFileName;
    protected List<String> imageFileNamesList;
    protected HashMap<String, float[]> imagePredictionsMap;
    protected HashMap<String, String> modelPerformanceMap;
    protected ImageProcessor imageProcessor;

    private List<String> readImageFileNames()
    protected void writeResultsToFiles()
    protected void writePredictionsToFile()
    private void writePerformanceToFile()
}

class Movenet extends TensorFlowLiteModel {
    public final static int TYPE_LIGHTNING = 1;
    public final static int TYPE_THUNDER = 2;
    public final static int DATA_TYPE_UINT8 = 1;
    public final static int DATA_TYPE_FLOAT16 = 2;
    public final static int DATA_TYPE_FLOAT32 = 3;
    private DataType modelDataType;
    private int inputWidth;
    private int inputHeight;

    protected Movenet(MainActivity, int, int)
    public void run()
}

class BlazePose extends TensorFlowLiteModel {
    public final static int TYPE_LITE = 1;
    public final static int TYPE_FULL = 2;
    public final static int TYPE_HEAVY = 3;
    private DataType modelDataType;
    private int inputWidth = 256;
    private int inputHeight = 256;
    private static final Map<Integer, Integer> COCO_BLAZEPOSE_KEYPOINTS_MAP;

    protected BlazePose(MainActivity, int)
    public void run()
}

class Yolo extends TensorFlowLiteModel {
    public final static int TYPE_NANO = 1;
    public final static int TYPE_SMALL = 2;
    public final static int TYPE_MEDIUM = 3;
    private DataType modelDataType;
    private int inputWidth = 320;
    private int inputHeight = 320;

    protected Yolo(MainActivity, int)
    public void run() {
}

@enduml